tap "caskroom/versions"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "ack"
brew "awscli"
brew "ctags"
brew "diff-so-fancy"
brew "fzf"
brew "gettext", link: false
brew "git-extras"
brew "git-lfs"
brew "gnupg"
brew "gnupg@1.4"
brew "python"
brew "grip"
brew "icu4c"
brew "maven"
brew "neovim"
brew "node", link: false
brew "postgresql", restart_service: true
brew "reattach-to-user-namespace"
brew "ruby"
brew "the_silver_searcher"
brew "thefuck"
brew "tmux"
brew "zsh"
brew "heroku/brew/heroku"
cask "amethyst"
cask "chromedriver"
cask "inkscape"
cask "java8"
cask "kap"
cask "pgadmin4"
cask "xquartz"
